CREATE TABLE IF NOT EXISTS bronze.transactions_raw (
	time_seconds DOUBLE,
	v1 DOUBLE,
	v2 DOUBLE,
	v3 DOUBLE,
	v4 DOUBLE,
	v5 DOUBLE,
	v6 DOUBLE,
	v7 DOUBLE,
	v8 DOUBLE,
	v9 DOUBLE,
	v10 DOUBLE,
	v11 DOUBLE,
	v12 DOUBLE,
	v13 DOUBLE,
	v14 DOUBLE,
	v15 DOUBLE,
	v16 DOUBLE,
	v17 DOUBLE,
	v18 DOUBLE,
	v19 DOUBLE,
	v20 DOUBLE,
	v21 DOUBLE,
	v22 DOUBLE,
	v23 DOUBLE,
	v24 DOUBLE,
	v25 DOUBLE,
	v26 DOUBLE,
	v27 DOUBLE,
	v28 DOUBLE,
	amount DOUBLE,
	transaction_class INT,
	ingestion_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
STORED AS PARQUET
TBLPROPERTIES (
	'parquet.compression'='SNAPPY',
	'external.table.purge'='true'
);