name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint com flake8
      run: |
        pip install flake8
        flake8 src/ --max-line-length=200

    - name: Build da imagem Docker
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/lapes-predictive-model:latest .

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push da imagem para Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/lapes-predictive-model:latest
